### ISSUE TITLE
Script retrieves Keyerror

### ISSUE THREAD

**Issue by JLUrsum** [larsenv/Kanopy-Downloader#5]
File "C:\Users\fsdf\Desktop\Kanopy-Downloader\Kanopy.py", line 25, in <module>
    lists = response.json()["list"]
KeyError: 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fsdf\Desktop\Kanopy-Downloader\Kanopy.py", line 36, in <module>
    lists["list"][0]["video"] = response.json()["video"]
KeyError: 'video'

**Comment by IanBotham** [comment]
I found I could get beyond this by fixing the url parsing code on line 14. The ID was the 8th element in my case.

However, the response to line 18 is not successful. This is what I get

`{'httpCode': 400, 'requestId': 'Root=1-677435a6-617498fe5e34ec5d7f73d9ee', 'status_code': 400, 'error_type': 'invalid', 'error_msg': 'Sorry', 'error_msg_long': 'Unknown error'}`
